name: Deploy Go Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Starting deployment..."

          # Navigate to project directory
          cd /opt/keyzy/server

          # Pull latest changes
          echo "Pulling latest code..."
          git pull origin main

          # Build the application
          echo "Building application..."
          go mod download
          go build -o keyzy-server main.go

          # Make executable
          chmod +x keyzy-server

          # Restart the service
          echo "Restarting service..."
          sudo systemctl restart keyzy

          # Wait a moment for service to start
          sleep 3

          # Check service status
          echo "Checking service status..."
          sudo systemctl is-active keyzy

          echo "Deployment completed successfully"
